version: '3.8'

services:
  app:
    build: .
    image: php:8.2-fpm
    container_name: laravel_app
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    volumes:
      - ./src/public:/var/www/html/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mariadb:10.6
    container_name: mariadb_server
    restart: always
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'laraveluser'
      MYSQL_PASSWORD: 'laravelpassword'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
